//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Photo { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int Course { get; set; }
        public string GroupName { get; set; }
        public Nullable<decimal> AverageScore { get; set; }
        public string Gender { get; set; }
        public int AddressID { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
